name: CI JPG

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - run: composer install
      - run: ./vendor/bin/phpunit

      - name: Executar tests amb informe JUnit
        run: ./vendor/bin/phpunit --log-junit resultats.xml

      - name: Pujar artefacte
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultats-JPG
          path: resultats.xml